FROM openjdk:8-jdk
RUN wget https://github.com/segmentio/chamber/releases/download/v2.1.0/chamber-v2.1.0-linux-amd64 -O /bin/chamber && chmod +x /bin/chamber
CMD ["/bin/sh", "-c", "chamber read -q $SERVICE $KEY"]
